#!/bin/bash
CONFIG=~/.config/fontconfig/fonts.conf
##find out what's the current font and update the radio list with the current font checked on app start
declare -a checkList=(Myanmar3
			Pyidaungsu
			Ours-Unicode
			TharLon
			Noto\ Sans\ Myanmar
			Myanmar\ Census
			MON3\ Anonta\ 1)

for i in "${!checkList[@]}"
do
	##check the current font in fontconfig
	if grep -q "${checkList[$i]}" "$CONFIG"; then
		checkList[$i]=true ##update the list with the current font checked
	fi
done

FONT=$(	zenity --list --radiolist --title="Myanmar Font Switcher" --width=100 --height=300 2> /dev/null --text="Choose a System Fallback Font you like..." --column="Check:" --column="Font Name:" "${checkList[0]}" "Myanmar3" "${checkList[1]}" "Pyidaungsu" "${checkList[2]}" "Ours-Unicode" "${checkList[3]}" "TharLon" "${checkList[4]}" "Noto Sans Myanmar" "${checkList[5]}" "Myanmar Census" "${checkList[6]}" "MON3 Anonta 1")

if [[ $FONT ]]; then
	if [ -f ~/.fonts.conf ]; then
		rm ~/.fonts.conf
		cp /usr/share/mmfs/fonts.conf $CONFIG
		echo ".fonts.conf is deprecated. Replaced new config in .config/fontconfig"
	fi
	if [ ! -f $CONFIG ]; then
		mkdir -p ~/.config/fontconfig
		cp /usr/share/mmfs/fonts.conf $CONFIG
		echo "Found no config. Created new."
	fi
	sed -i "s/Myanmar3/$FONT/g" $CONFIG
	sed -i "s/Pyidaungsu/$FONT/g" $CONFIG
	sed -i "s/Ours-Unicode/$FONT/g" $CONFIG
	sed -i "s/TharLon/$FONT/g" $CONFIG
	sed -i "s/Noto Sans Myanmar/$FONT/g" $CONFIG
	sed -i "s/Myanmar Census/$FONT/g" $CONFIG
	sed -i "s/MON3 Anonta 1/$FONT/g" $CONFIG
fi
